export interface BlogDetail {
    id: string,
    title: string,
    fulltitle: string,
    topic: string,
    description: string,
    subTopics: Array<String>,
    dataPath: string,
    publishBy: string,
    date : string,
    lastEdit: string,
    source: string;
    metadata : string;
    timeToRead: string;
    publisherid: string;
};


export const BlogDetailsList: Array<BlogDetail> = [
{
    "id": "1",
    "title": "URI: The Surgical Strike - A Riveting Bollywood Thriller(2019)",
    "fulltitle": "URI: The Surgical Strike (2019) - A Gripping Bollywood Action Thriller Igniting Patriotism and Resilience",
    "topic": "entertainment",
    "description":"this is the description.this is the description.this is the description.this is the description.this ",
    "subTopics": ["movie","bollywood"],
    "dataPath" : "blogs/entertainment/uri-movie-review/",
    "publishBy": "sourav ",
    "date": "2023-05-19",
    "lastEdit": "2023-05-19",
    "source":"",
    "metadata":"",
    "timeToRead":"2",
    "publisherid":"",
},
{
    "id": "2",
    "title": "The Ashes Series: A Historic Cricket Rivalry Rooted in Glory and Tradition",
    "fulltitle": "The Ashes Series: A Historic Cricket Rivalry Rooted in Glory and Tradition Between England and Australia",
    "topic": "sports",
    "description":"this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.this is the description.",
    "subTopics": ["cricket"],
    "dataPath" : "blogs/sports/the-ashes/",
    "publishBy": "admin",
    "date": "2023-05-19",
    "lastEdit": "2023-05-19",
    "source":"",
    "metadata":"",
    "timeToRead":"3",
    "publisherid":"",
},
{
    "id": "3",
    "title": "The World Test Championship: Triumph of Tradition and Intensity",
    "fulltitle": "The World Cricket Test Championship: A Triumph of Tradition and Intensity(India vs Australia from 6th to 11June)",
    "topic": "sports",
    "description":"this is the description.this is the description.this is the description.this is the description.this is the description.",
    "subTopics": ["cricket","indvsaus","wtc","testcricket"],
    "dataPath" : "blogs/sports/wtc-ind-vs-aus-2023-info/",
    "publishBy": "admin",
    "date": "2023-05-31",
    "lastEdit": "2023-05-31",
    "source":"",
    "metadata":"",
    "timeToRead":"2",
    "publisherid":"",
},
{
    "id": "4",
    "title": "Christopher Nolan's Oppenheimer: A Must-See Biopic for History Buffs",
    "fulltitle": "Cillian Murphy Stars in Christopher Nolan's Oppenheimer: A Gripping Look at the Man Who Made the Atomic Bomb",
    "topic": "entertainment",
    "description":"this is the description.this is the description.this is the description.this is the description.this ",
    "subTopics": ["movie","hollywood"],
    "dataPath" : "blogs/entertainment/christopher-nolan-oppenheimer-movie-plot-review-2023/",
    "publishBy": "admin",
    "date": "2023-05-31",
    "lastEdit": "2023-05-31",
    "source":"",
    "metadata":"",
    "timeToRead":"2",
    "publisherid":"",
},
{
    "id": "5",
    "title": "The Atomic Bombings of Hiroshima and Nagasaki: End of World War 2",
    "fulltitle": "The Atomic Bombings of Hiroshima and Nagasaki: Unleashing Destruction, Shaping History, and Pleading for Peace : End of World War II",
    "topic": "history",
    "description":"this is the description.this is the description.this is the description.this is the description.this ",
    "subTopics": ["atombomb","science","hirosima","nagasaki","worldwar2"],
    "dataPath" : "blogs/history/atom-bomb-1945-hiroshima-nagasaki/",
    "publishBy": "admin",
    "date": "2023-06-01",
    "lastEdit": "2023-06-01",
    "source":"",
    "metadata":"",
    "timeToRead":"4",
    "publisherid":"",
},
{
    "id": "6",
    "title": "Mastering the HR Round: A Guide to Ace Your Interview",
    "fulltitle": "Engineering HR Round Interview Prep: Unlocking Success through Research, Skills Showcase, and Confident Communication : Secure Your Dream Job",
    "topic": "career",
    "description":"this is the description.this is the description.this is the description.this is the description.this ",
    "subTopics": ["education","interview","hrround","engineering","placement"],
    "dataPath" : "blogs/career/hr-guide-interview-preparation-secure-job/",
    "publishBy": "admin",
    "date": "2023-06-01",
    "lastEdit": "2023-06-01",
    "source":"",
    "metadata":"",
    "timeToRead":"3",
    "publisherid":"",
},
{
    "id": "7",
    "title": "London's Finest Indian Restaurants: Top 10",
    "fulltitle": "London's Finest Top 10 Indian Restaurants: A Gastronomic Journey Through Vibrant Flavors in London,UK",
    "topic": "food",
    "description":"this is the description.this is the description.this is the description.this is the description.this ",
    "subTopics": ["top10inlondon","indianfood","top10indianfooduk","londonfood","london"],
    "dataPath" : "blogs/food/indian-desi-food-top-10-london-2023/",
    "publishBy": "admin",
    "date": "2023-06-02",
    "lastEdit": "2023-06-02",
    "source":"",
    "metadata":"",
    "timeToRead":"4",
    "publisherid":"",
},
{
    "id": "8",
    "title": "ONDC-Future of E-Commerce and Small Businesses in India",
    "fulltitle": "ONDC: The Future of E-Commerce in India - A Revolution for Small Businesses and Consumers : More Choices, Lower Prices, and Better Protection",
    "topic": "food",
    "description":"this is the description.this is the description.this is the description.this is the description.this ",
    "subTopics": ["ecommerce","ondc","retail"],
    "dataPath" : "blogs/food/ondc-future-of-e-commerce-in-india/",
    "publishBy": "admin",
    "date": "2023-06-02",
    "lastEdit": "2023-06-02",
    "source":"",
    "metadata":"",
    "timeToRead":"3",
    "publisherid":"",
},
{
    "id": "9",
    "title": "IRCTC Travel Insurance: Ensuring Safe Journeys with 35p",
    "fulltitle": "IRCTC Travel Insurance: Ensuring Safe Journeys with Financial Protection in Indian Railway: Starting with 35p only",
    "topic": "travel",
    "description":"this is the description.this is the description.this is the description.this is the description.this ",
    "subTopics": ["indianrailway","travelindia","travelinsurance"],
    "dataPath" : "blogs/travel/indian-railway-irctc-travel-insurance-35p-2023/",
    "publishBy": "admin",
    "date": "2023-06-04",
    "lastEdit": "2023-06-04",
    "source":"",
    "metadata":"",
    "timeToRead":"4",
    "publisherid":"",
},
]